services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wm-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8081:8081'
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - wm-network

volumes:
  db_data:

networks:
  wm-network:
    driver: bridge